# Pre-commit configuration for Django project
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
        exclude: ^(.*\.md|.*\.yml|.*\.yaml|.*\.txt)$
      - id: end-of-file-fixer
        exclude: ^(.*\.md|.*\.yml|.*\.yaml|.*\.txt)$
      - id: check-yaml
        args: [--unsafe]
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key

  # Local hooks - use tools from virtual environment
  - repo: local
    hooks:
      # Python import sorting (runs before Black)
      - id: isort
        name: isort
        entry: isort
        language: system
        args: [--profile=black, --line-length=88, --skip=migrations/]
        files: \.py$
        exclude: ^(migrations/|venv/|env/|\.venv/)

      # Python code formatting (runs after cleanup hooks)
      - id: black
        name: black
        entry: black
        language: system
        args:
          [
            --line-length=88,
            --target-version=py312,
            --extend-exclude=migrations/,
          ]
        files: \.py$
        exclude: ^(migrations/|venv/|env/|\.venv/)

      # Python linting
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        args:
          - --max-line-length=88
          - --extend-ignore=E203,W503,E501,C901,W504,E402
        files: \.py$
        exclude: ^(migrations/|venv/|env/|\.venv/)

      # Type checking
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        args: [--ignore-missing-imports, --no-strict-optional]
        files: \.py$
        exclude: ^(migrations/|venv/|env/|\.venv/)

      # Security scanning
      - id: bandit
        name: bandit
        entry: bandit
        language: system
        args: [-f, txt, -x, tests/, migrations/]
        pass_filenames: false
        files: \.py$
        exclude: ^(migrations/|venv/|env/|\.venv/|tests/)

      # Additional Python hooks
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        args:
          - --disable=C0114,C0116,R0903,W0613
        files: \.py$
        exclude: ^(migrations/|venv/|env/|\.venv/)

# Global configuration
default_stages: [commit]
fail_fast: false
minimum_pre_commit_version: "3.0.0"

# CI configuration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: []
  submodules: false
